export const ACCESS_ROLES = ["Owner", "Manager", "Member"];

export const PERMISSIONS = {
  TRACK_TIME: "track_time",
  VIEW_TIMESHEET: "view_timesheet",
  VIEW_WEEK_AHEAD: "view_week_ahead",
  MANAGE_SCHEDULE: "manage_schedule",
  SUBMIT_EXPENSES: "submit_expenses",
  REQUEST_TIME_OFF: "request_time_off",
  VIEW_DASHBOARD: "view_dashboard",
  VIEW_REPORTS: "view_reports",
  VIEW_ACTIVITY: "view_activity",
  USE_KIOSK: "use_kiosk",
  REVIEW_APPROVALS: "review_approvals",
  MANAGE_PROJECTS: "manage_projects",
  MANAGE_TEAM: "manage_team",
  MANAGE_SETTINGS: "manage_settings"
};

export const ROLE_PERMISSIONS = {
  Owner: Object.values(PERMISSIONS),
  Manager: [
    PERMISSIONS.TRACK_TIME,
    PERMISSIONS.VIEW_TIMESHEET,
    PERMISSIONS.VIEW_WEEK_AHEAD,
    PERMISSIONS.MANAGE_SCHEDULE,
    PERMISSIONS.SUBMIT_EXPENSES,
    PERMISSIONS.REQUEST_TIME_OFF,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_ACTIVITY,
    PERMISSIONS.REVIEW_APPROVALS,
    PERMISSIONS.MANAGE_PROJECTS,
    PERMISSIONS.MANAGE_TEAM
  ],
  Member: [
    PERMISSIONS.TRACK_TIME,
    PERMISSIONS.VIEW_TIMESHEET,
    PERMISSIONS.VIEW_WEEK_AHEAD,
    PERMISSIONS.SUBMIT_EXPENSES,
    PERMISSIONS.REQUEST_TIME_OFF,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ACTIVITY
  ]
};
