export function buildPagePropsBySection({
  activeProjects,
  activityItems,
  addActivityNote,
  addEntries,
  addEntry,
  addExpense,
  addProject,
  addProjectDependency,
  addScheduleItem,
  addTeamMember,
  addTeamMembers,
  addTimeOffRequest,
  clearActivity,
  clockInKiosk,
  clockOutKiosk,
  deleteProjectDependency,
  deleteScheduleItem,
  deleteTeamMember,
  employmentGrades,
  entries,
  expenses,
  handleNavigate,
  kioskSessions,
  moveScheduleItemToProject,
  onExportReportCsv,
  pendingApprovalCount,
  planningDays,
  projectDependencies,
  projects,
  reportFilters,
  scheduleItems,
  setReportFilters,
  teamMembers,
  timeOffRequests,
  timeTracking,
  todayKey,
  updateEmploymentGrade,
  updateEntry,
  updateEntryApproval,
  updateExpenseStatus,
  updateTeamMember,
  updateMemberStatus,
  updateProject,
  updateProjectStatus,
  updateProjectTags,
  updateScheduleItem,
  updateScheduleStatus,
  updateTimeOffStatus,
  weekDays,
  weeklyEntries,
  weeklyTotal
}) {
  return {
    "Time Tracker": {
      entries,
      projects,
      teamMembers,
      activeProjects,
      description: timeTracking.description,
      descriptionRef: timeTracking.descriptionRef,
      tagText: timeTracking.tagText,
      projectId: timeTracking.projectId,
      billable: timeTracking.billable,
      timerSeconds: timeTracking.timerSeconds,
      isRunning: timeTracking.isRunning,
      manualMode: timeTracking.manualMode,
      manualDate: timeTracking.manualDate,
      manualDuration: timeTracking.manualDuration,
      error: timeTracking.error,
      onDescriptionChange: timeTracking.setDescription,
      onTagTextChange: timeTracking.setTagText,
      onProjectChange: timeTracking.setProjectId,
      onBillableChange: timeTracking.setBillable,
      onManualModeChange: timeTracking.setManualMode,
      onManualDateChange: timeTracking.setManualDate,
      onManualDurationChange: timeTracking.setManualDuration,
      onStartStop: timeTracking.handleStartStop,
      onManualSave: timeTracking.handleManualSave,
      onRestartEntry: timeTracking.restartFromEntry,
      onUpdateEntry: updateEntry,
      onEntryApprovalChange: updateEntryApproval
    },
    Timesheet: {
      entries,
      projects,
      activeProjects,
      teamMembers,
      weekDays,
      onAddEntry: addEntry,
      onAddEntries: addEntries
    },
    "Week ahead": {
      entries,
      projects,
      teamMembers,
      weekDays: planningDays,
      scheduleItems,
      onAddSchedule: addScheduleItem,
      onUpdateEntry: updateEntry,
      onUpdateSchedule: updateScheduleItem
    },
    Schedule: {
      scheduleItems,
      projects,
      teamMembers,
      weekDays,
      projectDependencies,
      onAddSchedule: addScheduleItem,
      onUpdateSchedule: updateScheduleItem,
      onScheduleStatusChange: updateScheduleStatus,
      onMoveScheduleProject: moveScheduleItemToProject,
      onDeleteSchedule: deleteScheduleItem,
      onAddDependency: addProjectDependency,
      onDeleteDependency: deleteProjectDependency
    },
    Expenses: {
      expenses,
      projects,
      teamMembers,
      todayKey,
      onAddExpense: addExpense,
      onExpenseStatusChange: updateExpenseStatus
    },
    "Time Off": {
      timeOffRequests,
      teamMembers,
      todayKey,
      onAddTimeOff: addTimeOffRequest
    },
    Overview: {
      weeklyEntries,
      weeklyTotal,
      projects,
      expenses,
      pendingApprovalCount,
      activityItems,
      onNavigate: handleNavigate
    },
    Dashboard: {
      weeklyEntries,
      weeklyTotal,
      projects,
      expenses,
      pendingApprovalCount,
      activityItems,
      onNavigate: handleNavigate
    },
    Reports: {
      entries,
      projects,
      teamMembers,
      employmentGrades,
      scheduleItems,
      reportFilters,
      onExportReportCsv,
      onReportFiltersChange: setReportFilters
    },
    Activity: {
      activityItems,
      onAddActivityNote: addActivityNote,
      onClearActivity: clearActivity
    },
    Kiosks: {
      kioskSessions,
      projects,
      teamMembers,
      onClockIn: clockInKiosk,
      onClockOut: clockOutKiosk
    },
    Approvals: {
      entries,
      expenses,
      timeOffRequests,
      projects,
      teamMembers,
      onEntryApprovalChange: updateEntryApproval,
      onExpenseStatusChange: updateExpenseStatus,
      onTimeOffStatusChange: updateTimeOffStatus
    },
    Projects: {
      projects,
      entries,
      onAddProject: addProject,
      onUpdateProject: updateProject,
      onProjectStatusChange: updateProjectStatus,
      onProjectTagsChange: updateProjectTags
    },
    Team: {
      teamMembers,
      entries,
      employmentGrades,
      onAddTeamMember: addTeamMember,
      onAddTeamMembers: addTeamMembers,
      onUpdateTeamMember: updateTeamMember,
      onMemberStatusChange: updateMemberStatus,
      onDeleteTeamMember: deleteTeamMember,
      onEmploymentGradeChange: updateEmploymentGrade
    }
  };
}
